<?php
$siteSlug = $this->params()->fromRoute('site-slug');
$searchAction = $this->url('site/search', ['site-slug' => $siteSlug, 'controller' => 'SearchController', 'action' => 'search'], false);
?>

<!-- this overrides the default search -->
<div class="twelve columns">
    <form id="search-form" data-url="<?php echo $this->escapeHtml($searchAction); ?>" onsubmit="event.preventDefault();">
        <input class="search-text" type="text" autofocus>
        <button type="submit"><?php echo 'Search'; ?></button>
    </form>
</div>